import type { ItemExplorerFacade } from './item-explorer.facade';
import type { DeepReadonly } from './item-explorer.models';

type ReadonlyViewModelSlice<T> = {
  readonly [Key in keyof T]: DeepReadonly<T[Key]>;
};

export type ItemExplorerHeaderViewModel = ReadonlyViewModelSlice<
  Pick<
    ItemExplorerFacade,
    | 'allPersonalDataExportError'
    | 'allPersonalDataExportInProgress'
    | 'canEditExplorer'
    | 'canExportAllPersonalItemData'
    | 'canPublishExplorer'
    | 'canToggleReadOnlyPreview'
    | 'clearEmpiricalDifficultiesBusy'
    | 'clearEmpiricalDifficultiesError'
    | 'closeClearEmpiricalDifficultiesDialog'
    | 'closeDiscardDraftDialog'
    | 'closeDiscardPersonalItemDataDialog'
    | 'closeRenumberDialog'
    | 'confirmClearEmpiricalDifficulties'
    | 'confirmDiscardDraftDialog'
    | 'confirmDiscardPersonalItemDataChanges'
    | 'confirmRenumber'
    | 'draftSaveSuccessMessage'
    | 'discardAndLeave'
    | 'discardDraftDialogBusy'
    | 'discardDraftDialogError'
    | 'enableManualOrderMode'
    | 'explorerPublishedVersion'
    | 'explorerStatusLabel'
    | 'explorerUiStatus'
    | 'explorerVersion'
    | 'exportAllPersonalItemDataCsv'
    | 'exportPersonalItemDataXlsx'
    | 'filteredItems'
    | 'getRenumberingActionTitle'
    | 'getRenumberingBlockedMessage'
    | 'hasPendingDraftChanges'
    | 'isFullscreen'
    | 'isReadOnlyPreview'
    | 'isRenumberingBlocked'
    | 'itemListError'
    | 'lastDraftOperationError'
    | 'lastExplorerChangeInfo'
    | 'latestExplorerState'
    | 'leaveWithChangesDialogError'
    | 'leaveWithChangesDialogState'
    | 'moveSelectedItem'
    | 'numberingSuccessMessage'
    | 'onCsvFileSelected'
    | 'openClearEmpiricalDifficultiesDialog'
    | 'openColumnManager'
    | 'openDiscardExplorerDraftDialog'
    | 'openRenumberDialog'
    | 'openSavePreviewDialog'
    | 'personalDataLoadState'
    | 'personalExportError'
    | 'personalExportInProgress'
    | 'perspectiveSwitchBusy'
    | 'renumberBusy'
    | 'renumberError'
    | 'saveAndLeave'
    | 'selectedItem'
    | 'showClearEmpiricalDifficultiesDialog'
    | 'showDiscardDraftDialog'
    | 'showDiscardPersonalItemDataDialog'
    | 'showExplorerDraftStatus'
    | 'showHistory'
    | 'showLeaveWithChangesDialog'
    | 'showPersonalItemData'
    | 'showReadOnlyPreviewBanner'
    | 'showRenumberDialog'
    | 'sortField'
    | 'stayOnPage'
    | 'toggleFullscreen'
    | 'toggleReadOnlyPreview'
    | 'totalItemsCount'
  >
>;

export type ItemExplorerTableViewModel = ReadonlyViewModelSlice<
  Pick<
    ItemExplorerFacade,
    | 'addCustomTag'
    | 'addItemTag'
    | 'addPersonalItemTagToRow'
    | 'applyFilter'
    | 'availablePersonalTagsForRow'
    | 'availableTags'
    | 'canChangePersonalItemData'
    | 'canEditActiveCollection'
    | 'canEditExplorer'
    | 'canPreviewItem'
    | 'collectionBusy'
    | 'collectionLoadState'
    | 'columnFilters'
    | 'tableColumns'
    | 'enableItemCollections'
    | 'enableTags'
    | 'excludedItemsCount'
    | 'filterText'
    | 'filteredItems'
    | 'hiddenExcludedItemsCount'
    | 'hiddenMissingDifficultyItemsCount'
    | 'flushPersonalItemDataSave'
    | 'getItemRowId'
    | 'getMetaSortIndicator'
    | 'getMetadataColumnDisplayValue'
    | 'getColumnWidth'
    | 'getStickyTableColumnLeft'
    | 'getTableColumnSortIndicator'
    | 'getTableColumnDisplayValue'
    | 'getPersonalTagColor'
    | 'getPlayerTarget'
    | 'getSortIndicator'
    | 'hasEmpiricalDifficulty'
    | 'hasMeanTaskDifficulty'
    | 'hasPartialCredit'
    | 'isItemExcluded'
    | 'isStickyTableColumn'
    | 'isTableColumnSortable'
    | 'isItemInActiveCollection'
    | 'itemSubIdLabel'
    | 'itemListLoading'
    | 'itemListSlow'
    | 'itemTags'
    | 'onTableKeydown'
    | 'openDiscardPersonalItemDataDialog'
    | 'personalColumnFilters'
    | 'personalDataError'
    | 'personalDataLoadState'
    | 'personalDataSaveState'
    | 'personalItemCategoryLabel'
    | 'personalItemCategoryValues'
    | 'personalItemData'
    | 'personalItemTagLabel'
    | 'referenceNumberVisible'
    | 'removeItemTag'
    | 'removePersonalItemTagFromRow'
    | 'retryPersonalItemDataLoad'
    | 'retryPersonalItemDataSave'
    | 'selectItem'
    | 'selectedItem'
    | 'setColumnFilter'
    | 'setFilterText'
    | 'setPersonalColumnFilter'
    | 'setPersonalItemCategory'
    | 'setPersonalItemNote'
    | 'showExcludedItems'
    | 'showExplorerKeyboardHints'
    | 'showPersonalItemData'
    | 'showPlayerTargetInfo'
    | 'collectionViewMode'
    | 'activeItemCollection'
    | 'setCollectionViewMode'
    | 'sortBy'
    | 'sortByMeta'
    | 'sortTableColumn'
    | 'toggleItemInActiveCollection'
    | 'toggleShowExcludedItems'
  >
>;

export type ItemExplorerCollectionsViewModel = ReadonlyViewModelSlice<
  Pick<
    ItemExplorerFacade,
    | 'activateCollection'
    | 'activeCollectionId'
    | 'activeCollectionItems'
    | 'activeItemCollection'
    | 'clearActiveCollection'
    | 'canEditActiveCollection'
    | 'collectionBusy'
    | 'collectionError'
    | 'collectionLoadState'
    | 'collectionViewMode'
    | 'sharedCollectionsTruncated'
    | 'createCollection'
    | 'copyActiveCollection'
    | 'deleteActiveCollection'
    | 'enableItemCollections'
    | 'exportActiveCollection'
    | 'formatDuration'
    | 'itemCollections'
    | 'loadItemCollections'
    | 'removeRowFromActiveCollection'
    | 'removeRowsFromActiveCollection'
    | 'renameActiveCollection'
    | 'showCollectionDialog'
    | 'openCollectionDialog'
    | 'closeCollectionDialog'
    | 'setCollectionViewMode'
    | 'setActiveCollectionShared'
  >
>;

export type ItemExplorerPreviewViewModel = ReadonlyViewModelSlice<
  Pick<
    ItemExplorerFacade,
    | 'applyCustomPreviewTarget'
    | 'canEditExplorer'
    | 'canPreviewSelectedItem'
    | 'customPreviewTargetDraft'
    | 'filteredItems'
    | 'hasStoredPreviewTargetOverride'
    | 'isItemExcluded'
    | 'isPreviewLoading'
    | 'itemSubIdLabel'
    | 'loadAllResponseStates'
    | 'navigateItem'
    | 'onPagingModeChange'
    | 'onPlayerLoaded'
    | 'onPreviewTargetSelectionChange'
    | 'openCodingOverlay'
    | 'pagingMode'
    | 'playerHeight'
    | 'playerSrcDoc'
    | 'previewTargetDefaultOptionLabel'
    | 'previewTargetOptions'
    | 'previewUnavailableMessage'
    | 'previewUnavailableReason'
    | 'previewLoadPhase'
    | 'previewSlow'
    | 'previewUpdateInProgress'
    | 'resetPreviewTargetSelection'
    | 'resetResponseState'
    | 'saveCurrentResponseState'
    | 'selectedIndex'
    | 'selectedItem'
    | 'selectedItemTarget'
    | 'selectedItemUsesDerivedTarget'
    | 'selectedPreviewTarget'
    | 'selectedPreviewTargetId'
    | 'setCustomPreviewTargetDraft'
    | 'setMetadataDrawerOpen'
    | 'setPagingMode'
    | 'setSelectedPreviewTargetId'
    | 'shouldRenderPlayerFrame'
    | 'showMetadataDrawer'
    | 'showPlayerTargetInfo'
    | 'showPreviewTargetSelector'
    | 'toggleSelectedItemExclusion'
  >
>;

export type ItemExplorerCodingDialogViewModel = ReadonlyViewModelSlice<
  Pick<
    ItemExplorerFacade,
    | 'closeCodingOverlay'
    | 'codingSearchText'
    | 'codingVariableFocus'
    | 'codingVariableFocusMessage'
    | 'currentCodingSchemeAsText'
    | 'filteredCodingSchemeAsText'
    | 'getCodingVariableDisplayLabel'
    | 'getCodingSortIndicator'
    | 'itemSubIdLabel'
    | 'preferManualCodingInstructions'
    | 'selectedItem'
    | 'setCodingSearchText'
    | 'shouldShowAutomaticCodingRules'
    | 'shouldShowVariableManualInstruction'
    | 'showOverlay'
    | 'showGeneralCodingInstructions'
    | 'showPlayerTargetInfo'
    | 'toggleCodingSort'
  >
>;

export type ItemExplorerMetadataDrawerViewModel = ReadonlyViewModelSlice<
  Pick<
    ItemExplorerFacade,
    | 'currentUnitMetadata'
    | 'extractLabel'
    | 'extractValueText'
    | 'selectedItem'
    | 'setMetadataDrawerOpen'
    | 'showMetadataDrawer'
  >
>;

export type ItemExplorerUploadDialogsViewModel = ReadonlyViewModelSlice<
  Pick<
    ItemExplorerFacade,
    | 'closeUploadErrorDialog'
    | 'closeUploadReport'
    | 'errorMessage'
    | 'getUploadSuccessBookletSummary'
    | 'getUploadSuccessFieldSummary'
    | 'showErrorDialog'
    | 'showUploadReport'
    | 'uploadResult'
  >
>;

export type ItemExplorerColumnManagerDialogViewModel = ReadonlyViewModelSlice<
  Pick<
    ItemExplorerFacade,
    | 'allTableColumns'
    | 'canResetMetadataSettings'
    | 'closeColumnManager'
    | 'columnFilterText'
    | 'filteredAllColumns'
    | 'getColumnWidth'
    | 'isColumnVisible'
    | 'metadataSettings'
    | 'moveColumnDown'
    | 'moveColumnUp'
    | 'resetToDefault'
    | 'saveMetadataSettings'
    | 'setColumnFilterText'
    | 'setColumnWidth'
    | 'showColumnManager'
    | 'toggleColumnVisibility'
    | 'toggleReferenceNumberVisibility'
    | 'tableColumns'
  >
>;

export type ItemExplorerResponseStateDialogsViewModel = ReadonlyViewModelSlice<
  Pick<
    ItemExplorerFacade,
    | 'allResponseStates'
    | 'closeDeleteConfirmDialog'
    | 'closeRawDataOverlay'
    | 'closeSaveConfirmDialog'
    | 'confirmDeleteResponseState'
    | 'confirmDialogError'
    | 'confirmDialogState'
    | 'confirmSaveResponseState'
    | 'selectedItem'
    | 'showDeleteConfirmDialog'
    | 'showRawDataOverlay'
    | 'showSaveConfirmDialog'
  >
>;

export type ItemExplorerHistoryDialogViewModel = ReadonlyViewModelSlice<
  Pick<
    ItemExplorerFacade,
    | 'closeHistoryOverlay'
    | 'exportHistoryCsv'
    | 'filteredHistoryEntries'
    | 'historyError'
    | 'historyFilterFrom'
    | 'historyFilterTo'
    | 'historyFilterType'
    | 'historyFilterUser'
    | 'historyLoading'
    | 'setHistoryFilter'
    | 'showHistory'
    | 'showHistoryOverlay'
  >
>;

export type ItemExplorerDraftDialogsViewModel = ReadonlyViewModelSlice<
  Pick<
    ItemExplorerFacade,
    | 'cancelSavePreviewDialog'
    | 'confirmSaveExplorerDraft'
    | 'draftPreviewSummary'
    | 'explorerPublishedVersion'
    | 'explorerVersion'
    | 'showSavePreviewDialog'
  >
>;
